### ISSUE TITLE
disable-changelog option also prevents creating a release commit

### ISSUE THREAD

**Issue by es50678** [ridedott/release-me-action#1410]
We are running a set up where we use a `pre-release` action and we want to pass `disable-changelog` to it because we keep getting merge conflicts on the changelog files. However, we noticed a small issue:

When we use the `disable-changelog` action like this:
```
    - name: Create github release
      id: github-release
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      uses: ridedott/release-me-action@v3
      with:
        release-branches: '["master", { "name": "cmd-2451-add-preprod", "prerelease": true }]'
        disable-changelog: true

```
Our release commit never gets committed anymore. Which is a bit odd but not a show killer. The github prerelease still gets created and tagged properly.

<img width="935" alt="Screenshot 2023-08-21 at 10 50 04 AM" src="https://github.com/ridedott/release-me-action/assets/17823824/fe221927-b9e2-4bed-8587-901a97c88a4a">

We are using:
````
ridedott/release-me-action: v3
node: v16
